/**
 * Central icon system — Phosphor icons, one family, consistent weights.
 * Use weight="duotone" for feature/list icons, "regular" for chrome,
 * "fill" for active tab, "bold" for small glyphs.
 */
export {
  House,
  CalendarBlank,
  List,
  ChartBar,
  GearSix,
  Plus,
  CaretRight,
  CaretLeft,
  X,
  Check,
  CheckCircle,
  Warning,
  WarningCircle,
  Sparkle,
  TrendUp,
  TrendDown,
  Wallet,
  Receipt,
  Bell,
  ArrowsClockwise,
  Trash,
  PencilSimple,
  DeviceMobile,
  Lightning,
  Car,
  Television,
  ForkKnife,
  House as HouseRent,
  CurrencyDollar,
  ArrowRight,
  EnvelopeSimple,
  AppleLogo,
  GoogleLogo,
  ShoppingBag,
  Coffee,
  CreditCard,
} from "@phosphor-icons/react";
